-- A exécuter dans la console :
-- cat TABLEAU_DE_BORD_JARNOT_DEV_2_Création_Utilisateur_DEV.sql | mysql


DROP USER IF EXISTS 'DEV'@'localhost';
CREATE USER 'DEV'@'localhost' IDENTIFIED BY 'pw@DEV';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_DEV.* TO 'DEV'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'DEV'@'localhost';

DROP USER IF EXISTS 'USER'@'localhost';
CREATE USER 'USER'@'localhost' IDENTIFIED BY 'pw@USER';
GRANT SELECT ON TABLEAU_DE_BORD_JARNOT_DEV.* TO 'USER'@'localhost';
GRANT UPDATE ON TABLEAU_DE_BORD_JARNOT_DEV.T_OPERATIONS TO 'USER'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'USER'@'localhost';

DROP USER IF EXISTS 'BE'@'localhost';
CREATE USER 'BE'@'localhost' IDENTIFIED BY 'pw@BE';
GRANT SELECT, INSERT ON TABLEAU_DE_BORD_JARNOT_DEV.T_PROJETS TO 'BE'@'localhost';
GRANT SELECT, INSERT ON TABLEAU_DE_BORD_JARNOT_DEV.T_PAQUETS TO 'BE'@'localhost';
GRANT SELECT, INSERT ON TABLEAU_DE_BORD_JARNOT_DEV.T_ETAPES TO 'BE'@'localhost';
GRANT SELECT, INSERT ON TABLEAU_DE_BORD_JARNOT_DEV.T_OPERATIONS TO 'BE'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'BE'@'localhost';

DROP USER IF EXISTS 'SUPERVISOR'@'localhost';
CREATE USER 'SUPERVISOR'@'localhost' IDENTIFIED BY 'pw@SUPERVISOR';
GRANT SELECT ON TABLEAU_DE_BORD_JARNOT_DEV.T_OPERATIONS  TO 'SUPERVISOR'@'localhost';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_DEV.T_COMPTES  TO 'SUPERVISOR'@'localhost';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_DEV.T_COMPTE_PROFIL  TO 'SUPERVISOR'@'localhost';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_DEV.T_PROFILS  TO 'SUPERVISOR'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'SUPERVISOR'@'localhost';


