-- A exécuter dans la console :
-- cat *TErr



CREATE USER IF NOT EXISTS 'DEV'@'localhost' IDENTIFIED BY 'pw@DEV';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_TEST.* TO 'DEV'@'localhost';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'USER'@'localhost' IDENTIFIED BY 'pw@USER';
GRANT ALL PRIVILEGES ON TABLEAU_DE_BORD_JARNOT_TEST.* TO 'USER'@'localhost';
FLUSH PRIVILEGES;